### PR TITLE
Improved parsing of database.yml

### PR DESCRIPTION
**Pull request by erw7**
Corresponding to the parsing of the reference with the anchor/aliases
rails 4.2 to generate the next database.yml

<pre><code class="language-yaml">default: &default
  adapter: postgresql
...

development:
  &lt;&lt;: *default
  database: depot_development
</code></pre>

Fixed a bug that parsing is terminate by a comment line or empty line

<pre><code class="language-yaml">development:
  database: depot_development
  # comment

  username: root
</code></pre>

rinari-parse-yaml return ((&quot;database&quot; . &quot;depot_development&quot;)), but ((&quot;database&quot; . &quot;depot_development&quot;) (&quot;username&quot; . &quot;root&quot;)) is correct.

Fixed a bug that include comment and trailing spaces on the value

<pre><code class="language-yaml">development:
  database: depot_development # comment
  username: root<span style="background-color: green;color: green;">     </span>
</code></pre>

rinari-parse-yaml return ((&quot;database&quot; . &quot;depot_development # comment&quot;) (&quot;username&quot; . &quot;root&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&quot;)), but ((&quot;database&quot; . &quot;depot_development&quot;) (&quot;username&quot; . &quot;root&quot;)) is correct.

### CODE REVIEW

**Comment by purcell** [comment]
Thanks! I decided that it might be better to just ask Ruby to handle this for us, so I committed 4862bb4 in place of this fix. Let me know if you have any problems with my fix. :)

**Comment by erw7** [comment]
Thanks. Your code is more elegant than me code and work fine.

**Comment by erw7** [comment]
rinari-sql fails with (wrong-type-argument sequencep 5432), if defined port in database.yml.
We need number-to-string.
<pre><code>--- a/rinari.el
+++ b/rinari.el
@@ -425,7 +425,7 @@ Looks up login information from your conf/database.sql file."
           (when (string-match-p "sqlite" adapter)
             ;; Always expand sqlite DB filename relative to RAILS_ROOT
             (setq sql-database (expand-file-name sql-database (rinari-root))))
-          (set (make-local-variable 'sql-server) (if port (concat server ":" port) server))
+          (set (make-local-variable 'sql-server) (if port (concat server ":" (number-to-string port)) server))
           (funcall
            (intern (concat "sql-"
                            (cond</code></pre>

**Comment by purcell** [comment]
Done - thanks.

**Pull request closed without merging**
